
/* !this class is auto generated by electron boilerplate */

import { createRoot } from 'react-dom/client';
import App from './App';

const container = document.getElementById('root')!;
const root = createRoot(container);
root.render(<App />);

window.electron.ipcRenderer.on('ipc-example', (arg) => {
  console.log(arg);
});



window.electron.ipcRenderer.myPing();
